import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

[env]
  TERM = "xterm-256color"

[window]
dynamic_padding = false
decorations = "buttonless"
startup_mode = "Maximized"
opacity = 0.5
blur = true
option_as_alt = "Both"

  [window.padding]
  x = 1
  y = 1

[font]
size = 16

  [font.normal]
  family = "Hack Nerd Font"
  style = "Regular"

  [font.bold]
  family = "Hack Nerd Font"
  style = "Bold"

  [font.italic]
  family = "Hack Nerd Font"
  style = "Italic"

  [font.offset]
  x = 1
  y = 1

  [font.glyph_offset]
  x = 0
  y = 0


# [keyboard]
# bindings = [
#   { key = "F",  mods = "Alt",           chars = "\u001bf"                       },
#   { key = "B",  mods = "Alt",           chars = "\u001bb"                       },
#   { key = "I",  mods = "Alt",           chars = "\u001bi"                       }
# ]

[shell]
program = "/bin/zsh"
# args = []
